name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [reverseproxy, udagram-api-user, udagram-api-feed, udagram-frontend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for ${{ matrix.app }}
      run: |
        echo "Building and pushing Docker image for ${{ matrix.app }}"
        cd ${{ matrix.app }} # Navigate to the app directory
        docker build -t lcd1502/${{ matrix.app }}:latest . # Build with the 'latest' tag
        docker push lcd1502/${{ matrix.app }}:latest # Push to DockerHub
