name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - app: udagram-reverseproxy
            image_name: reverseproxy
          - app: udagram-api-user
            image_name: udagram-api-user
          - app: udagram-api-feed
            image_name: udagram-api-feed
          - app: udagram-frontend
            image_name: udagram-frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for ${{ matrix.app }}
      run: |
        echo "Building and pushing Docker image for ${{ matrix.app }}"
        cd ${{ matrix.app }} # Navigate to the app directory
        docker build -t lcd1502/${{ matrix.image_name }}:latest . # Build with the correct image name and 'latest' tag
        docker push lcd1502/${{ matrix.image_name }}:latest # Push to DockerHub
